version: "3"
services:
    dev:
        build:
            context: .
        tty: true
        volumes:
            - ./package.json:/work/package.json
            - ./yarn.lock:/work/yarn.lock
            - ./css:/work/css
            - ./img:/work/img
            - ./sass:/work/sass
            - ./index.html:/work/index.html
